### ISSUE TITLE
I am trying to run Scorbot in my college in 2022

### ISSUE THREAD

**Issue by amit-420** [baijuchaudhari/sboter4u#1]
Could you tell if there is any way to do it only using ROS indigo

**Comment by baijuch** [comment]
I don't know. Actually, it was used in my university project during which i had access to it. So, now, i can't really help you further on this.

**Comment by baijuch** [comment]
> Could you tell if there is any way to do it only using ROS indigo

Like i said before, i don't remember it. Fact is, i had very little time experimenting with it. You can refer my files to save your time, but i can't really help you beyond that point.
